export const data = [
  {
    id: 1,
    title: "Birthdays",
    live: "https://1birthdays.netlify.app/",
    url: "https://github.com/rasulovfazliddin/1.birthdays",
    img: "./images/1.png",
  },
  {
    id: 2,
    title: "Tours",
    url: "https://github.com/rasulovfazliddin/2.tours",
    img: "./images/2.png",
    live: "https://2tours.netlify.app/",
  },
  {
    id: 3,
    title: "Reviews",
    url: "https://github.com/rasulovfazliddin/3.reviews",
    img: "./images/3.png",
    live: "https://3reviews.netlify.app/",
  },
  {
    id: 4,
    title: "Questions",
    url: "https://github.com/rasulovfazliddin/4.questions",
    img: "./images/4.png",
    live: "https://4questions.netlify.app/",
  },
  {
    id: 5,
    title: "Menu",
    url: "https://github.com/rasulovfazliddin/5.menu",
    img: "./images/5.png",
    live: "https://5menu.netlify.app/",
  },
  {
    id: 6,
    title: "Tab Info",
    url: "https://github.com/rasulovfazliddin/6.tab-infos",
    img: "./images/6.png",
    live: "https://6tab-infos.netlify.app/",
  },
  {
    id: 7,
    title: "Slider",
    url: "https://github.com/rasulovfazliddin/7.slider",
    img: "./images/7.png",
    live: "https://7slider.netlify.app/",
  },
  {
    id: 8,
    title: "Color Generator",
    url: "https://github.com/rasulovfazliddin/8.color-generator",
    img: "./images/8.png",
    live: "https://8color-generator.netlify.app/",
  },
  {
    id: 9,
    title: "Grocery List",
    url: "https://github.com/rasulovfazliddin/9.grocery-list",
    img: "./images/9.png",
    live: "https://9grocery-list.netlify.app/",
  },
  {
    id: 10,
    title: "Navbar",
    url: "https://github.com/rasulovfazliddin/10.navbar",
    img: "./images/10.png",
    live: "https://10navbar.netlify.app/",
  },
  {
    id: 11,
    title: "Sidebar",
    url: "https://github.com/rasulovfazliddin/11.sidebar",
    img: "./images/11.png",
    live: "https://11sidebar.netlify.app/",
  },
  {
    id: 12,
    title: "Strapi",
    url: "https://github.com/rasulovfazliddin/12.strapi",
    img: "./images/12.png",
    live: "https://12strapi.netlify.app/",
  },
  {
    id: 13,
    title: "Cart",
    url: "https://github.com/rasulovfazliddin/13.cart",
    img: "./images/13.png",
    live: "https://13cart.netlify.app/",
  },
];
